### ISSUE TITLE
`cap production deploy`が失敗する

### ISSUE THREAD

**Issue by yosei** [yosei/stack.lmlab.net#13]
`cap staging deploy` は問題ないのに何故か？

```
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host sakura16: rake exit status: 1
rake stdout: Nothing written
rake stderr: rake aborted!
Bundler::GemNotFound: Could not find minitest-5.8.3 in any of the sources
/opt/stack.lmlab.net/releases/20160106015055/config/boot.rb:3:in `<top (required)>'
/opt/stack.lmlab.net/releases/20160106015055/config/application.rb:1:in `<top (required)>'
/opt/stack.lmlab.net/releases/20160106015055/Rakefile:4:in `<top (required)>'
LoadError: cannot load such file -- bundler/setup
/opt/stack.lmlab.net/releases/20160106015055/config/boot.rb:3:in `<top (required)>'
/opt/stack.lmlab.net/releases/20160106015055/config/application.rb:1:in `<top (required)>'
/opt/stack.lmlab.net/releases/20160106015055/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by yosei** [comment]
http://stack.lmlab.net/stacks/15
